
os: linux
dist: xenial

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
addons:
  sonarcloud:
    organization: "groypyspoopyboi"
    token:
   secure: "cbRPZNrLZcAJdscjKoRdksdHv7SPzveCEx3XFpyCQQqv2nB+SPKNmQhl0IJFyy/6ADPRy2J8Yewcht423MrSAxGmCR9ujiaA/KadGyUwNhMkj4j0Glj/uJbmhOdkKdo38y3HjEik85/zd1wAagtm3oif4Vw7ANIqb5UTJPWLbFznw8cdniZ8l/85TMz8DXsVKH1PMFKFQtk7HK8d1v0k70Sk+0TI55mFB9teSD2cuA6EHB4O2WDyZK3c9Y3MWtQyvPVNB1ha0mq5VV5ort38dMuJvSY1iLapVHf4HRzcG7cYmqkdFV3HTpjtLQT/yIU2ejy/Zik5hNKFxSXvcfOiBJ7UuYJN8JdJESA78hEozcTd4mfQfwS+CK0w0TJaI3VTttFp9hQpEsbhIaLs72rZuOdrcKaXiHGIAPGwBBtvh9Ddwvh7uYIXBaBFTeZXQj77+CcoSzXsnPyaiV+r/5xaO82c2xN0fF6D6oDsVLpsZNan8tbjfJQhffM4/8jEo0BxC6Cz1tXJLmuGor75KnzN8eVz3noFcRGZn4hAfHsYZua2GV5o0RVK6dRFad5EJCdRxrgdnc2e1YWEsYPIoX7j0TGTCaTrb3hgu4ncFtkifAbwtmKFGvd/zPTVc8htVgqLPs1hAyTx6SbW9W9SqVftJ8+ccvpsdtMSnEoK+X9kKJA="
 # encrypted value of your token

script:
  - qmake
  - make
  - ./tests/tests
  
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
  