language:
- cpp
before_install:
- pip install --user cpp-coveralls
addons:
  sonarcloud:
    organization: groypyspoopyboi
    token:
      secure: "EbZ41ytNTRX0NeKYvLilmXYbLgJf8cZLfjIDlRBVbhvzWYLjBW99kMNoZi5FRp52YYnAPxwArVx/+Od5n3JEZfCbuwUmy5Hwgcr9E1Yfnm+wVZ2OgTRC55s8+NYpqskK4mj5afl/aL6pzEKY9uZbiD/MrLGrJ0JURWmCBC2h0hZlZgQV7u80YF956dfGgC4Fqmc3zH9vPV+qQ5nzVV4zZWgmafSDJ3pKp1VJjRaQ8ebXIPn9CvG/aqRZwrPPUP8CWu2EO7mfve0zjNZcemYF92zLmSdCQYpbhB8Fs34HGf43ZXBhCyGG8ephTEMWEmaz1inpyo0CdbyuPb47SJhj6HAE/zZINA60t0G+eDl0Duk77I3zlUqupNH3z7G8M122nP+Ues9JPCH2h8gPrCfbBQLkzWFZ1dNelDyt06lFkT5NBC2wbTSh3Z/nRfPomEMjsnaawmODrx5e0eu3iI/wA39XglKD+cCAZH/2Wre63TLY2iOhG66v5gqQwMc9wZlFr63ZaV3R1vfcgmFAtn7czZ0k2GH4f3eYTBy1L8kLzfL9C3EWhE7+oIR2g3zAcUp5HFamSy6oui/PybZNDtFZVAHjIRhA3JFxaAcRjTQjvzr1RoF3AedKGOiJP03Xfa/7DLp6vOUZB6bIehL5GAOUXUT4NskmDxLAYdxQPEP2SiQ="
script:
- qmake
- make
- "./tests/tests"
after_success:
- coveralls --root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
env:
  global:
  - secure: "fo5/7vIkWQI+EoLOIhRhswPd9BzRnqyktQnaxcIL6kvD/Jnl2q3MTGrVQHruN50elhBWpu3nQ4h/NGQbe8S4N0e2xBNyXm+9dYqLJlLUSNZBNTfy6tLJ0zW+b0ZDzhUkFXBdc9B8wGMUcpjqptopH2FR66gODSy8EJjjjs0Fux0m7MKo5VsIDCc70+aUC7EuvZfRD25bepNPuOuSJtGOQb6SJ3xCQhCGaQVaw0/4QO6r3iAt3edFtjX1d7maObtRfInuZLWok5gfyewAXA2wpRdjxMaRSqNgW8vBrnXMc4KYTZrAwef+65aVwXbBaMdn/C2wzP3ZN7qZNqW4C7108mzc1SpSyqLpnSk60oYAw1qFNV3ORmCTI6pcz3hy/4UznSNbFo+YAIe8cJiQBv2HtdZamRWGylFXsfg/T4N2w/SdTyBA4BbseM9NhFoKJY6TsilC/PE8XTh3IRSELe7HYiIh0gotLJtowq4NC80jKilba9Rryaj3rdazjgC1GUyBEHIN8Ez+5Mc09/j+6qb2BcbodZWZ8wHZrloF4VimkEEOvOiGb8vWdDbiUxYGTTCQe/D0pVH3coc55qIMDHnJC7fcBVWHkyDLKIS6gPPPM6ULQfb3xnyPdGWpXIuGsA5IBCTq8uJ3o/Lo2yzp23lpAYz2z04O7rJzlZznH2+M/b0="
  - secure: "PFdKqK8/jGnRfe1vl3XovWRVqITlOcQufS5ahu6Bbqq9wh+dDfDMERHrSKbg+nfgjwbkV8Dob/bYb/PDNtniiowjfu1zGRfmtn77HO27GlXAULFJ5ha/hpg+7B3MNoxEGCWS6d9S6M7RwyA/F0pCIjXNIQs+VzRTmpQ3RVMVeJ4iixGf29tkW0bLhcKAVe8XR4F6LxqzSMF0luemniX0GDXZBvsj8oEoXT7u/PlET1NGnVoUMrblRcROHP8tfMEvMSiUm5lwEpO3emDK5LDjgU7G31Vauf2WAz/XVUcV1T/IC8Y0J0SLVYWYCBQ16xmeT9Ojk3TUxZftipduEDHZueU+2AjN8wyCP4sxHMGLqXBQo7SN0aGqdK6gw3LnWByV+yi8Beftx8qfuarF++BBgdEZzkwETk1mi0jd4oofXb0wldmH77m1Yw3qkXnv95elXUrKRy+YxHROQEfUvnEf65pHMYCCRj+uUCcCL5QnD44iUnm10h5XEWIw+oKV5i1PRHK1J7IBFaSce2aIUgMsP87SNoz2PJ1Z0E65N/tttIk+VwbZA1GVFu9jhit/fRU3pcbXOWUMq3m3BB2UVI+XtycwhhiQD5BQ8fx158utTkNGX37z7wiH+mRcA+cgF6Z2vSokxmEqVOpZY8jK6IGAMO+QyNrkXJvi5p7mhNSYYcQ="
