language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
addons:
  sonarcloud:
    organization: "groypyspoopyboi"
    token:
      secure: "S+d0E+V4DLji5eIZIVkhftASTtaHT0VMLYRtEQ3GIvrtKs11+4cJcZpZLKLXk1URxqE57BTz2SiOn6JVSAo/xGInRz08arEUc99e8FyBo7a4CNbV/uP/zya/eNKn1y5qX7Ft//KZ8jDKg0wC3a7mLxlfCd/G78SFMTphd3lu3A6nqZO1hxH7Ac6oPJsNCBgDwZtbQjYzfNA0uIdd9f945yaLhecN2kEhLoPVjNPeZNG1w5TTP81mPK42WEAccBuFZ4Q5kjDgRf+EjVtO+iuPtPa7TrzLuetz8HCkBEXf4p+FdoGXkLT/dxxxa1k37y6vXvR3d4jbYMcgDDnkorUv2myhVjqmyxN1DDxvUT/NJY8q2j7cwH4Zu3vG/ZMBPPN6WMDdAP1IiQ4O3fBOMeNWhW4v1PoTLVunYJNnKu7gvU1FBt87zi+DAckzkH0VJZAI8NgFGAx/BCUXjn99ccoevs222uGOQm8pKUMN8syAPSY4/HFF1vXt0w2gfl+YvhGTqskfppC8nnAy9PdH+qCVPhM+RSPZuzz3wHCW+hULKQMjXpezPfp3A34b+GIe7BrZCHpA1GHvwzwyrgZrjv74R0nOfH3cQ0X/ycCUUtuJhdfNacuuUmvTRCXEK9BlA7UEWOYwd1xUhXy+eK2/BO+47Vkl0dD3HHOb/RzP/n7KP1U=" # encrypted value of your token
      
script:
  - qmake
  - make
  - ./tests/tests
  
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
  